### PR TITLE
addresses #400 -- adds Plan column to homepage with links to Vulcan

### PR DESCRIPTION
**Pull request by wdower**
Signed-off-by: Will Dower <wdower@mitre.org>

### CODE REVIEW

**Comment by em-c-rod** [comment]
Can you change the spacing on the "inputs" column to line up?

**Comment by ejaronne** [comment]
Note: 

Keep "Aggregated Data" *only* under Visualizate column.
Keep "Security Tool Output" *only* under Normalize column
"Based on Standards" should span Plan, Harden, Validate columns

**Comment by ejaronne** [comment]
Plan Tools tile:
**Vulcan**
Generate and tailor security guidance based on Security Requirements Guides (SRGs)

**Training Classes** (link to SAF train)
Learn to use and develop SAF security tools appropriate to your mission

Validate Tools tile, *add*:
**Vulcan**
Generate InSpec validation code to current, tailored, or authored standards

**Comment by ejaronne** [comment]
Do you have an icon for Vulcan?

**Pull request merged**
