### PR TITLE
FAQ tab

### PR DESCRIPTION
**Pull request by wdower**
Added mockup of FAQ tab. Refactored each tab to reuse a single Header component for reusability.

Mockup of an FAQ tab as per conversation with @ejaronne.

Signed-off-by: Will Dower <wdower@mitre.org>

### CODE REVIEW

**Comment by aaronlippold** [comment]
I almost want to say that the first level dropdown is not needed so that when we enter the FAQ we get the list of items in the major sections and we can expand from there.

**Comment by wdower** [comment]
Sure. Maybe we don't even want to categorize the questions by topic at all. Not sure how many we will have (especially after more info is added to other parts of the site i.e. tutorial articles)

**Comment by aaronlippold** [comment]
No, I think sections and categories are goood but just don't see a need yet
to close it all - aka user experience thing. When we get huge amounts of
articles then maybe it makes sense.

Aaron
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by wdower** [comment]
Still needs more questions but we can add them as we go

**Pull request merged**
